apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: pre
spec:
  selector:
    matchLabels:
      run: php-apache
  replicas: 1
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 2m
          requests:
            cpu: 1m
