apiVersion: v1
kind: Pod
metadata:
  name: test-pd1
  namespace: pre
  labels:
    app: test-nginx

spec:
  containers:
  - image: nginx
    name: test-container1
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pd2
  namespace: pre
  labels:
    app: test-apache

spec:
  containers:
  - image: httpd
    name: test-container2
