apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-claim
  namespace: pre
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
